apiVersion: v1
kind: Service
metadata:
  name: fastapi-lab-service
  labels:
    app: fastapi-lab
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fastapi-lab
  type: LoadBalancer
